In [4]:
import pandas as pd
import matplotlib.pyplot as plt

file = pd.ExcelFile('basedados.xlsx')
print(file.sheet_names)

data = file.parse(0)

# Mostrando as 5 primeiras linhas do dataset
data.head()

# Primeiro, precisamos saber com o que exatamente estamos trabalhando, logo, devemos abrir o dataset disponibilizado
# para termos real noção do que se trata.

# Agora aberto, podemos ver o que as colunas representam e seus respectivos valores. Com isso podemos facilmente ver que
# o dataset se trata das informações sobre sorteios de MegaSenas, que tais sorteios ocorrem semanalmente, e que a quantia
# de ganhadores de sena é muito menor que a de ganhadore de Quina, que por sua vez é muito menor que Ganhadores de Quadra.

['MegaSena']

,Concurso,Data Sorteio,Dezena1,Dezena2,Dezena3,Dezena4,Dezena5,Dezena6,Arrecadacao_Total,Ganhadores_Sena,Rateio_Sena,Ganhadores_Quina,Rateio_Quina,Ganhadores_Quadra,Rateio_Quadra,Acumulado,Valor_Acumulado,Estimativa_Prêmio
0,1,1996-03-11,41,5,4,52,30,33,0.0,0,0.00,17,39158.92,2016,330.21,SIM,1714650.23,0
1,2,1996-03-18,9,39,37,49,43,41,0.0,1,2307162.23,65,14424.02,4488,208.91,NÃO,0.00,0
2,3,1996-03-25,36,30,10,11,29,47,0.0,2,391192.51,62,10515.93,4261,153.01,NÃO,0.00,0
3,4,1996-04-01,6,59,42,27,1,5,0.0,0,0.00,39,15322.24,3311,180.48,SIM,717080.75,0
4,5,1996-04-08,1,19,46,6,16,2,0.0,0,0.00,98,5318.10,5399,96.53,SIM,1342488.85,0

In [5]:
# Geramos as informações gerais do dataset
print(data.info())

print("\nPrimeira MegaSena a ocorrer:", data['Data Sorteio'].iloc[0])
print("Mais recente MegaSena a ocorrer:", data['Data Sorteio'].iloc[-1])

# Com estas novas informações, agora descobrimos que o dataset contém registro de TODAS as MegaSenas que ocorreram
# desde seu início até a publicação do dataset em questão. Também sabemos agora quando ocorreu a primeira MegaSena.
# 11 de março de 1996
# de Março de 1996 para Março de 2018, também sabemos que se passaram mais de 22 anos!

# Houveram 2025 sorteios de lá pra cá!! Dá pra acreditar?!

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2025 entries, 0 to 2024
Data columns (total 18 columns):
Concurso             2025 non-null int64
Data Sorteio         2025 non-null datetime64[ns]
Dezena1              2025 non-null int64
Dezena2              2025 non-null int64
Dezena3              2025 non-null int64
Dezena4              2025 non-null int64
Dezena5              2025 non-null int64
Dezena6              2025 non-null int64
Arrecadacao_Total    2025 non-null float64
Ganhadores_Sena      2025 non-null int64
Rateio_Sena          2025 non-null float64
Ganhadores_Quina     2025 non-null int64
Rateio_Quina         2025 non-null float64
Ganhadores_Quadra    2025 non-null int64
Rateio_Quadra        2025 non-null float64
Acumulado            2025 non-null object
Valor_Acumulado      2025 non-null float64
Estimativa_Prêmio    2025 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(11), object(1)
memory usage: 300.6+ KB
None

Primeira MegaSena a ocorrer: 1996-03-11 00:00:00
Mais recente MegaSena a ocorrer: 2018-03-24 00:00:00

In [6]:
print("A média de ganhadores da Sena é:", data['Ganhadores_Sena'].mean())
print("A média de ganhadores da Quina é:", data['Ganhadores_Quina'].mean())
print("A média de ganhadores da Quadra é:", data['Ganhadores_Quadra'].mean())

# Como no início vimos somente as 5 primeiras MegaSenas, estávamos apenas supondo sobre sobre as informações, gerais.
# Porém, nesta célula, mostramos que é muito mais raro alguém ganhar a Sena do que a Quina, e é muito mais fácil alguém
# ganhar a Quina do que a Quadra.

# Pode-se notar também, que ,estatisticamente, a cada 100 sorteios, só 34 possuem ganhadores.

A média de ganhadores da Sena é: 0.3412345679012346
A média de ganhadores da Quina é: 112.9753086419753
A média de ganhadores da Quadra é: 7281.367901234568

In [7]:
# Nesta célula, analisamos quantos ganhadores da Sena houveram em todos os sorteios.
vencedores = 0
for i in data.Ganhadores_Sena:
    vencedores = vencedores + i
print(vencedores)

# Ou seja, em 2025 sorteios através de 22 anos, cada qual recebendo as milhões de apostas das pessoas,
# somente, 691 pessoas (no máximo*) conseguiram acertar os 6 números.

691/22

# Aproximadamente, é como se a cada ano 31 pessoas conseguissem acertar os 6 números exatos. Mesmo que hajam dezenas
# de sorteios num único ano, com milhões de apostadores.

## *: Pois apesar de altamente improvável, ainda é possível que uma mesma pessoa tenha ganho a Sena mais de 1 vez.
##   Por isso que no máximo 691 pessoas.


# Engraçado é perceber que se tomássemos probabilidade como uma certeza absoluta, num exemplo em que estivessemos na
# última semana do ano, e somente 11 pessoas acertaram a Sena durante o ano inteiro, as chances de terem muitos
# ganhadores no sorteio desta semana em questão são muito boas em comparação com o resto. Então seria recomendado que
# você, como pessoa, devesse apostar na MegaSena. É muito louco isso de probabilidade e chances. KKKKKK

691

31.40909090909091

In [57]:
# Considerando a repercussão que a MegaSena possui, e a quanto tempo ainda se mantém de pé, muito provavelmente
# eles devem ganhar bastante dinheiro com os sorteios Acumulados.

acumulados = 0
for i in data.Acumulado:
    if i == "SIM":
        acumulados = acumulados + 1
# Declaramos a variável concurso para receber a quantidade de concursos que houveram        
concursos = len(data.Concurso)

print(acumulados)
print(int (acumulados*100/concursos), "%")

# Agora vemos claramente que existe muitaaaa vantagem para quem organiza a MegaSena.
# Aproximadamente, apenas 1 a cada 4 sorteios possui um ganhador para a Sena, nos outros 3, a empresa recebe um lucro
# multi-milionário.

1548
76 %

In [8]:
# Neste célula analisamos o quanto de dinheiro a empresa organizadora da MegaSena teve de pagar aos ganhadores
# ao longo de seus anos de existência.
valor_Sena = 0
valor_Quina = 0
valor_Quadra = 0

# Pego a quantidade de ganhadores e multiplico por quanto cada um ganha, logo, terei o total de determinado prêmio.
for i, valor in enumerate(data.Ganhadores_Sena):
    valor_Sena = valor_Sena + (valor * data.Rateio_Sena[i])
    
for i, valor in enumerate(data.Ganhadores_Quina):
    valor_Quina = valor_Quina + (valor * data.Rateio_Quina[i])
    
for i, valor in enumerate(data.Ganhadores_Quadra):
    valor_Quadra = valor_Quadra + (valor * data.Rateio_Quadra[i])
    
print("Distribuíram ", int (valor_Quadra), " reais no total para ganhadores da Quadra.\n")
print("Distribuíram ", int (valor_Quina), " reais no total para ganhadores da Quina.\n")
print("Distribuíram ", int (valor_Sena), " reais no total para ganhadores da Sena.\n")

custo_total = valor_Quadra + valor_Quina + valor_Sena
print("Ou seja, tiveram um custo total de: ", int(custo_total), " de reais")

# Podemos ver que ao longo dos seus 22 anos de existência, a MegaSena premiou uma quantia muito alta de dinheiro.

Distribuíram  5153872752  reais no total para ganhadores da Quadra.

Distribuíram  4005254754  reais no total para ganhadores da Quina.

Distribuíram  12085571422  reais no total para ganhadores da Sena.

Ou seja, tiveram um custo total de:  21244698928  de reais

In [9]:
# Como 21 bilhões e 240 milhões é um valor incrivelmente alto, me perguntei se a MegaSena realmente saía no lucro,
# ou se ela na verdade ganhava pouco.
# Resultado? Não podia estar mais enganado!

# Aqui faço a contagem do quanto a MegaSena ganhou em todos os sorteios.
acumulado_valor = 0
for i in data.Valor_Acumulado:
    acumulado_valor = acumulado_valor + i
    
print(int(acumulado_valor))

lucro = acumulado_valor - custo_total
print(int(lucro))
# Ao subtrairmos o valor de ganho total da MegaSena, com o valor de custo total, ou seja, o tanto de dinheiro que
# a empresa premiou á ganhadores, obtivemos o lucro total da empresa.

# O qual pudemos que perceber que era nada mais nada menos do que em torno de 3 bilhões e 730 milhões de reais, de LUCRO.
int(lucro/22)
# Mesmo que dividíssemos esse valor nos 22 anos, ainda seriam mais de 169 milhões por ano, apenas por gerenciarem aposas KKKKKKKKKKK.

24977500438
3732801510

169672795

In [109]:
# Para os superticiosos, podemos tentar analisar quais os números que saíram com mais frequência nos sorteios.

cols = ['Dezena1','Dezena2','Dezena3','Dezena4','Dezena5','Dezena6'] 
dezenas = data[cols]

dezenas = dezenas.unstack().value_counts()

# E então achamos os 6 números mais sorteados de todos os sorteios.

seis_maiores_frequencias = dezenas[0:6]
print(seis_maiores_frequencias)
print("\n")
# Caso você seja supersticioso, e acredite que ao usar os 6 números mais frequentes vocẽ terá mais chance,
# então o recomendo que aposte nos números: 5, 53, 10, 23, 4, 54.

seis_menores_frequencias = dezenas[-6:]
print(seis_menores_frequencias)
# E caso acredite que os 6 menos usados dão azar,
# aconselho-o a jamais apostar nos númeors: 9, 15, 21, 22, 55, 26

5     233
53    230
10    227
23    224
4     224
54    221
dtype: int64


9     183
15    183
21    178
22    177
55    174
26    164
dtype: int64

In [10]:
# Aqui é impressa o dataset como um todo, na forma de um DataFrame
pd.DataFrame(data)

,Concurso,Data Sorteio,Dezena1,Dezena2,Dezena3,Dezena4,Dezena5,Dezena6,Arrecadacao_Total,Ganhadores_Sena,Rateio_Sena,Ganhadores_Quina,Rateio_Quina,Ganhadores_Quadra,Rateio_Quadra,Acumulado,Valor_Acumulado,Estimativa_Prêmio
0,1,1996-03-11,41,5,4,52,30,33,0.0,0,0.000000e+00,17,39158.92,2016,330.21,SIM,1.714650e+06,0
1,2,1996-03-18,9,39,37,49,43,41,0.0,1,2.307162e+06,65,14424.02,4488,208.91,NÃO,0.000000e+00,0
2,3,1996-03-25,36,30,10,11,29,47,0.0,2,3.911925e+05,62,10515.93,4261,153.01,NÃO,0.000000e+00,0
3,4,1996-04-01,6,59,42,27,1,5,0.0,0,0.000000e+00,39,15322.24,3311,180.48,SIM,7.170808e+05,0
4,5,1996-04-08,1,19,46,6,16,2,0.0,0,0.000000e+00,98,5318.10,5399,96.53,SIM,1.342489e+06,0
5,6,1996-04-15,19,40,7,13,22,47,0.0,0,0.000000e+00,109,7214.66,7147,110.03,SIM,2.286166e+06,0
6,7,1996-04-22,56,38,21,20,3,5,0.0,0,0.000000e+00,100,8746.05,5736,152.48,SIM,3.335692e+06,0
7,8,1996-04-29,53,17,38,4,47,37,0.0,0,0.000000e+00,60,16084.11,5262,183.40,SIM,4.493748e+06,0
8,9,1996-05-06,55,43,56,54,8,60,0.0,0,0.000000e+00,17,60043.79,2175,469.31,SIM,5.718641e+06,0
9,10,1996-05-13,25,4,18,57,21,38,0.0,0,0.000000e+00,251,6638.45,12590,132.35,SIM,1.333477e+07,0
10,11,1996-05-20,25,15,58,37,59,38,0.0,1,1.559137e+07,148,12706.05,9442,199.16,NÃO,0.000000e+00,0
11,12,1996-05-27,20,27,43,16,19,4,0.0,0,0.000000e+00,108,6791.17,6454,113.64,SIM,8.801362e+05,0
12,13,1996-06-03,47,32,50,54,18,56,0.0,0,0.000000e+00,43,20543.98,2934,301.09,SIM,1.940205e+06,0
13,14,1996-06-10,16,2,27,47,23,53,0.0,0,0.000000e+00,85,10458.19,5323,167.00,SIM,3.006941e+06,0
14,15,1996-06-17,60,12,33,52,35,51,0.0,0,0.000000e+00,57,17919.89,3931,259.84,SIM,4.232661e+06,0
15,16,1996-06-24,60,58,49,32,20,34,0.0,0,0.000000e+00,31,33307.13,3250,317.70,SIM,5.471687e+06,0
16,17,1996-07-01,10,20,6,19,51,13,0.0,1,6.789869e+06,144,7628.37,9376,117.16,NÃO,0.000000e+00,0
17,18,1996-07-08,37,36,56,27,42,23,0.0,0,0.000000e+00,52,13763.52,4484,159.61,SIM,8.588435e+05,0
18,19,1996-07-15,5,25,12,10,60,24,0.0,0,0.000000e+00,159,5380.14,9250,92.48,SIM,1.050627e+07,0
19,20,1996-07-22,25,28,30,33,51,11,0.0,0,0.000000e+00,72,15486.97,5728,194.67,SIM,1.184434e+07,0
20,21,1996-07-29,49,46,6,53,33,36,0.0,0,0.000000e+00,63,17694.19,5030,221.62,SIM,1.318202e+07,0
21,22,1996-08-05,9,38,56,1,31,46,0.0,0,0.000000e+00,47,27212.90,4865,262.90,SIM,1.471683e+07,0
22,23,1996-08-12,17,52,51,59,39,37,0.0,0,0.000000e+00,74,20198.46,4897,305.23,SIM,1.651045e+07,0
23,24,1996-08-19,1,8,14,28,33,43,0.0,1,1.866168e+07,227,7897.31,13486,132.93,NÃO,0.000000e+00,0
24,25,1996-08-25,56,50,55,54,24,43,0.0,0,0.000000e+00,28,26338.50,2741,269.06,SIM,8.849735e+05,0
25,26,1996-09-01,50,53,57,10,58,22,0.0,0,0.000000e+00,16,52473.74,1823,460.55,SIM,1.892469e+06,0
26,27,1996-09-08,44,33,13,51,17,20,0.0,0,0.000000e+00,99,9306.24,6466,142.49,SIM,2.998051e+06,0
27,28,1996-09-15,60,6,22,3,24,54,0.0,0,0.000000e+00,50,19749.22,4895,201.73,SIM,4.183003e+06,0
28,29,1996-09-22,14,56,58,8,43,3,0.0,1,5.401794e+06,44,23083.15,5248,193.53,NÃO,0.000000e+00,0
29,30,1996-09-29,38,50,7,29,15,14,0.0,0,0.000000e+00,80,11347.74,5885,154.26,SIM,1.012752e+07,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,2017-12-13,56,21,20,7,40,24,48458620.0,0,0.000000e+00,144,19401.81,4933,809.08,SIM,3.312983e+07,39000000
1996,1997,2017-12-16,14,7,35,1,31,46,54280324.0,0,0.000000e+00,86,36389.62,6280,711.89,SIM,3.889471e+07,43500000
1997,1998,2017-12-19,57,21,24,52,25,8,38499475.0,0,0.000000e+00,61,36388.03,4810,659.24,SIM,4.298357e+07,48000000
1998,1999,2017-12-21,42,38,49,15,50,37,50491038.5,0,0.000000e+00,73,39877.23,4434,937.89,SIM,1.390996e+08,280000000
1999,2000,2017-12-31,6,37,34,10,3,17,890947368.5,17,1.804228e+07,4862,10565.03,173428,423.12,NÃO,0.000000e+00,2000000
2000,2001,2018-01-03,22,20,52,60,42,36,17710070.0,0,0.000000e+00,12,85088.83,1214,1201.53,SIM,1.880911e+06,4500000
2001,2002,2018-01-06,59,46,28,38,4,30,28829944.5,0,0.000000e+00,24,69257.39,2214,1072.51,SIM,4.942817e+06,8500000
2002,2003,2018-01-10,40,50,43,28,51,34,30509412.5,0,0.000000e+00,16,109937.90,1865,1347.38,SIM,8.183091e+06,12000000
2003,2004,2018-01-13,45,35,1,23,5,14,38638484.5,3,4.095573e+06,79,28198.54,6444,493.85,NÃO,0.000000e+00,12000000
2004,2005,2018-01-17,22,19,33,11,53,34,32721132.5,0,0.000000e+00,44,42875.50,4052,665.11,SIM,1.119825e+07,15000000
2005,2006,2018-01-20,20,9,1,14,54,25,38569461.0,0,0.000000e+00,71,31319.78,5500,577.58,SIM,1.529455e+07,20000000
2006,2007,2018-01-24,41,14,54,4,39,58,38825178.0,0,0.000000e+00,42,53296.38,3340,957.42,SIM,1.941801e+07,24000000
2007,2008,2018-01-27,27,22,58,33,59,42,43671250.0,0,0.000000e+00,49,51384.62,4215,853.36,SIM,2.405615e+07,30000000
2008,2009,2018-01-31,1,48,50,44,37,46,47352865.0,0,0.000000e+00,46,59350.17,3665,1064.16,SIM,4.251297e+07,48000000
2009,2010,2018-02-03,18,56,8,34,39,10,61968606.0,0,0.000000e+00,106,33705.40,7436,686.38,SIM,4.909439e+07,56000000
2010,2011,2018-02-06,28,35,58,54,2,32,43455856.5,0,0.000000e+00,119,21054.02,5949,601.64,SIM,5.370965e+07,59000000
2011,2012,2018-02-08,11,51,36,8,35,27,60329097.5,0,0.000000e+00,107,32506.98,6828,727.72,SIM,6.011695e+07,70000000
2012,2013,2018-02-10,6,36,53,30,56,23,69104360.5,0,0.000000e+00,159,25057.74,8465,672.37,SIM,6.745623e+07,71000000
2013,2014,2018-02-14,46,32,16,56,40,53,52356503.5,0,0.000000e+00,46,65621.53,4140,1041.61,SIM,9.219062e+07,100000000
2014,2015,2018-02-17,18,58,32,39,27,17,116332797.0,1,1.045458e+08,130,51593.19,12558,762.98,NÃO,0.000000e+00,3000000
2015,2016,2018-02-21,11,17,48,18,4,21,26614714.0,0,0.000000e+00,64,23975.93,4543,482.51,SIM,2.826635e+06,6200000
2016,2017,2018-02-24,56,10,11,2,38,24,34810982.5,0,0.000000e+00,123,16317.17,6125,468.10,SIM,6.523762e+06,11000000
2017,2018,2018-02-28,55,11,27,22,25,59,37486974.0,0,0.000000e+00,83,26039.70,4661,662.42,SIM,1.050509e+07,15000000
2018,2019,2018-03-03,41,46,54,59,23,52,45790930.5,0,0.000000e+00,54,48889.92,4043,932.84,SIM,3.279459e+07,40000000
2019,2020,2018-03-07,2,46,57,60,48,36,53716386.5,0,0.000000e+00,46,67325.96,4530,976.66,SIM,3.849958e+07,45000000
2020,2021,2018-03-10,32,37,40,60,7,14,61453154.0,0,0.000000e+00,101,35079.74,6982,724.93,SIM,4.502626e+07,52000000
2021,2022,2018-03-14,28,60,52,45,4,48,64651783.0,0,0.000000e+00,79,47183.15,6343,839.50,SIM,5.189265e+07,60000000
2022,2023,2018-03-17,23,56,8,7,1,6,73781900.5,2,2.986436e+07,217,19603.05,13622,446.11,NÃO,0.000000e+00,3000000
2023,2024,2018-03-21,29,16,20,35,47,23,25175416.0,0,0.000000e+00,45,32255.05,3221,643.75,SIM,2.128445e+07,25000000
2024,2025,2018-03-24,52,56,4,24,46,55,43865881.5,0,0.000000e+00,53,47718.26,3730,968.62,SIM,2.594326e+07,30000000

In [57]:
# Aqui veremos qual foi o sorteio que teve a maior quantidade de ganhadores da Sena, Quina e Quadra

# Criamos uma função que baseado na coluna do DataFrame recebido, iremos achar seu maior valor obtido e seu respectivo
# índice

#-----------------Início da função--------------#
def maioria(x):
    ganhadores = {'maior quantidade':0, 'índice do sorteio':0}
    for i, winners in enumerate(x):
        if(ganhadores['maior quantidade'] < winners):
            ganhadores['maior quantidade'] = winners
            ganhadores['índice do sorteio'] = i
    
    return ganhadores
#---------------Fim da função-----------------#
Sena_ganha = maioria(data.Ganhadores_Sena)
Quina_ganha = maioria(data.Ganhadores_Quina)
Quadra_ganha = maioria(data.Ganhadores_Quadra)

print(Sena_ganha['maior quantidade'], "ganhadores na Sena foi o máximo obtido.")
print("O dia com mais ganhadores na Sena, foi em", data['Data Sorteio'].iloc[Sena_ganha['índice do sorteio']])
print("\n")

print(Quina_ganha['maior quantidade'], "ganhadores na Quina foi o máximo obtido.")
print("O dia com mais ganhadores na Quina, foi em", data['Data Sorteio'].iloc[Quina_ganha['índice do sorteio']])
print("\n")

print(Quadra_ganha['maior quantidade'], "ganhadores na Quadra foi o máximo obtido.")
print("O dia com mais ganhadores na Quadra, foi em", data['Data Sorteio'].iloc[Quadra_ganha['índice do sorteio']])

# Como resultado, vimos que em 31 de dezembro de 2017 ocorreu o sorteio com maior quantidade de ganhadores na Sena.
# Engraçado notar que foi justamente na virada de ano.

#???? Estranhamente, no 31 de dezembro de 2017, houve a maior quantidade registrada de ganhadores, tanto na Sena,
# quanto na Quina, quanto na Quadra. Por que será que isso ocorreu? Somente com os dados que temos, não podemos
# inferir a verdadeira razão por trás disso, mas podemos criar hipóteses. Será que houve algum tipo de vazamento de dados??
# Afinal, é uma discrepância enorme entre as quantidades de outros ganhadores. Será que pode ser justamente por ser a Mega da Virada??

17 ganhadores na Sena foi o máximo obtido.
O dia com mais ganhadores na Sena, foi em 2017-12-31 00:00:00


4862 ganhadores na Quina foi o máximo obtido.
O dia com mais ganhadores na Quina, foi em 2017-12-31 00:00:00


173428 ganhadores na Quadra foi o máximo obtido.
O dia com mais ganhadores na Quadra, foi em 2017-12-31 00:00:00

In [67]:
# Nesta célula tentamos analisar se a discrepância previamente assumida, é real.

# Definimos uma função que acha a segunda maior quantidade de ganhadores dentre todos os sorteios, assim como seu índice
# Temos que achar o segundo maior, logo, o maior que seja diferente do maior previamente achado
def segn_maior(x):
    ganhadores = {'maior quantidade':0, 'índice do sorteio':0}
    
    # A maior quantia de ganhadores (maior msm)
    real_maior = maioria(x)
    for i, winners in enumerate(x):
        if(ganhadores['maior quantidade'] < winners and winners != real_maior['maior quantidade']):
            ganhadores['maior quantidade'] = winners
            ganhadores['índice do sorteio'] = i
    
    return ganhadores
    
Sena_sec = segn_maior(data.Ganhadores_Sena)
Quina_sec = segn_maior(data.Ganhadores_Quina)
Quadra_sec = segn_maior(data.Ganhadores_Quadra)

print(Sena_sec['maior quantidade'], "ganhadores na Sena foi a segunda maior quantia obtida.")
print("O dia que teve essa quantia, foi em", data['Data Sorteio'].iloc[Sena_sec['índice do sorteio']])
print("\n")

print(Quina_sec['maior quantidade'], "ganhadores na Quina foi a segunda maior quantia obtida.")
print("O dia que teve essa quantia, foi em", data['Data Sorteio'].iloc[Quina_sec['índice do sorteio']])
print("\n")

print(Quadra_sec['maior quantidade'], "ganhadores na Quadra foi a segunda maior quantia obtida.")
print("O dia que teve essa quantia, foi em", data['Data Sorteio'].iloc[Quadra_sec['índice do sorteio']])

print("\n\n", 17-15)
print(4862-3001)
print(173428-168546)

## Vemos que realmente existe uma discrepância entre o sorteio com mais ganhadores de Sena, Quina e Quadra
# em relação aos sorteios com as segundas maiores quantias de ganhadores.

# Para ganhadores da Sena, o maior quantia é 17, e a segunda é 15. Diferença -> 2
# Para ganhadores da Quina, o maior quantia é 4862, e a segunda é 3001. Diferença -> 1861
# Para ganhadores da Quadra, o maior quantia é 173428, e a segunda é 168546. -> 4882

# Ou seja, algo deve ter ocorrido no sorteio do dia 31 de Dezembro de 2017. Outra possibilidade, seria os dados liberados pela
# caixa econômica estarem incorretos. Afinal, é muito suspeito esse fato.

15 ganhadores na Sena foi a segunda maior quantia obtida.
O dia que teve essa quantia, foi em 2004-01-14 00:00:00


3001 ganhadores na Quina foi a segunda maior quantia obtida.
O dia que teve essa quantia, foi em 2001-10-31 00:00:00


168546 ganhadores na Quadra foi a segunda maior quantia obtida.
O dia que teve essa quantia, foi em 2014-12-31 00:00:00


 2
1861
4882